# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!

inhibit_all_warnings!

target 'QuizMeUp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for QuizMeUp
  pod 'IQKeyboardManagerSwift'
  pod 'SwiftLint'
  pod 'R.swift'
  pod 'Alamofire'
  pod 'AlamofireNetworkActivityLogger'
  pod 'SwiftDate'
  pod 'SnapKit'
  pod 'Kingfisher'
  pod 'NVActivityIndicatorView'
  pod 'NVActivityIndicatorView/Extended'
  pod 'SwiftyUserDefaults'
  pod 'JGProgressHUD'
end

post_install do |installer|
 installer.pods_project.targets.each do |target|
  target.build_configurations.each do |config|
   config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
  end
 end
end
